aviferdman/Workshop-on-Software-Engineering-Project

TradingSystem/TradingSystemTests/IntegrationTests/ConcurrentTests/AssinationConcurrentTests.cs, TradingSystem/TradingSystemTests/IntegrationTests/ConcurrentTests/PurchaseConcurrentTests.cs, TradingSystem/TradingSystemTests/IntegrationTests/ConcurrentTests/UserManagementConcurrentTests.cs
Added concurrent tests for: 
1. signIn / login
2. purchasing a product
3. Assignation of manager
=> concurrent tests added

TradingSystem/AcceptanceTests/Tests/Market/Shop/Products/UseCase_EditShopProductInShop.cs, TradingSystem/AcceptanceTests/Tests/Market/Shop/Products/UseCase_RemoveProductFromShop.cs
=> Accptance tests

TradingSystem/AcceptanceTests/AppInterface/UserBridge/UserBridgeAdapter.cs, TradingSystem/AcceptanceTests/Tests/Market/ShoppingCart/UseCase_PurchaseCart.cs
* Further adaptation to service layer changes: Sign up method
* Fixed tests which expected different output than they should have: entry in history instead of empty history
=> Acceptance tests - fixes

TradingSystem/AcceptanceTests/Tests/Market/ShoppingCart/ProductsForEdit.cs, TradingSystem/AcceptanceTests/Tests/Market/ShoppingCart/UseCase_AddProductToCart_TestLogic.cs, TradingSystem/AcceptanceTests/Tests/Market/ShoppingCart/UseCase_EditShoppingCart.cs, TradingSystem/AcceptanceTests/Tests/Market/ShoppingCart/UseCase_ViewShoppingCart.cs, TradingSystem/AcceptanceTests/Tests/Market/UseCase_SearchProduct.cs, TradingSystem/TradingSystem/PublisherComponent/Publisher.cs
* Fixed teardown issues which caused some tests to fail due to left over side effects
=> Acceptance tests bug fixes

TradingSystem/TradingSystem.WebClient/package-lock.json, TradingSystem/TradingSystem.WebClient/package.json, TradingSystem/TradingSystem.WebClient/src/App.js, TradingSystem/TradingSystem.WebClient/src/components/passwordFields.js, TradingSystem/TradingSystem.WebClient/src/components/simpleAlertDialog.js, TradingSystem/TradingSystem.WebClient/src/formFieldInfo.js, TradingSystem/TradingSystem.WebClient/src/pages/Login.js, TradingSystem/TradingSystem.WebClient/src/pages/Signup.js, TradingSystem/TradingSystem.WebClient/src/routes.js, TradingSystem/TradingSystem.WebClient/src/style/forms.js
Implementation of the logic in the client for the signup and login pages
=> Client logic

TradingSystem/TradingSystem.WebApi/ControllerBase.cs, TradingSystem/TradingSystem.WebApi/ControllerExtensions.cs, TradingSystem/TradingSystem.WebApi/Controllers/ProductsController.cs, TradingSystem/TradingSystem.WebApi/Controllers/StoresController.cs, TradingSystem/TradingSystem.WebApi/DTO/ProductDTO.cs, TradingSystem/TradingSystem.WebApi/DTO/ProductSearchCriteria.cs, TradingSystem/TradingSystem.WebApi/DTO/StoreInfoDTO.cs, TradingSystem/TradingSystem.WebApi/Startup.cs, TradingSystem/TradingSystem.WebApi/StoresData.json, TradingSystem/TradingSystem.WebApi/TradingSystem.WebApi.csproj, TradingSystem/TradingSystem.WebApi/productData.json, TradingSystem/TradingSystem.WebClient/package-lock.json, TradingSystem/TradingSystem.WebClient/src/App.js, TradingSystem/TradingSystem.WebClient/src/components/searchBar.js, TradingSystem/TradingSystem.WebClient/src/globalContext.js, TradingSystem/TradingSystem.WebClient/src/pages/Login/Login.js, TradingSystem/TradingSystem.WebClient/src/pages/Signup/Signup.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/MyStores.js, TradingSystem/TradingSystem.WebClient/src/pages/mainPage/Home.css, TradingSystem/TradingSystem.WebClient/src/pages/mainPage/Home.js, TradingSystem/TradingSystem/Service/StoreData.cs
* Added logic to query the server for product searching and retrieving all the currently logged-in user stores.
* Refactored the code to use react context for passing the username to all components
=> Client logic - connecting to the web API server

TradingSystem/TradingSystem.WebClient/src/components/AddProduct.css, TradingSystem/TradingSystem.WebClient/src/components/EditProduct.js, TradingSystem/TradingSystem.WebClient/src/components/Products.js, TradingSystem/TradingSystem.WebClient/src/pages/mainPage/Home.css
=> edit added

TradingSystem/AcceptanceTests/AppInterface/MarketBridge/IMarketBridge.cs, TradingSystem/AcceptanceTests/AppInterface/MarketBridge/MarketBridgeAdapter.cs, TradingSystem/AcceptanceTests/AppInterface/MarketBridge/MarketBridgeProxy.cs, TradingSystem/AcceptanceTests/AppInterface/UserBridge/UserBridgeAdapter.cs, TradingSystem/AcceptanceTests/Tests/User/UseCase_SignUp.cs, TradingSystem/TradingSystem.WebApi/Controllers/StoresController.cs, TradingSystem/TradingSystem/Service/MarketGeneralService.cs
* Adjusted calls for async methods to either await them or block until the result is available (acceptance test and web API serve)
=> Acceptance tests and web API async calls adjustments

TradingSystem/TradingSystem.WebApi/Program.cs, TradingSystem/TradingSystem.WebApi/Startup.cs
* Turned on debug mode on the DAL
=> Web API server - set DAL debug on

TradingSystem/TradingSystem.WebApi/Controllers/ProductsController.cs, TradingSystem/TradingSystem.WebApi/Controllers/ShoppingCartController.cs, TradingSystem/TradingSystem.WebApi/Controllers/StoresController.cs, TradingSystem/TradingSystem.WebApi/DTO/ShoppingCart/ShoppingCartDTO.cs, TradingSystem/TradingSystem.WebApi/DTO/ShoppingCart/ShoppingCartEditProductDTO.cs, TradingSystem/TradingSystem.WebClient/src/App.js, TradingSystem/TradingSystem.WebClient/src/components/AddManager.js, TradingSystem/TradingSystem.WebClient/src/components/AddOwner.js, TradingSystem/TradingSystem.WebClient/src/components/AddProduct.js, TradingSystem/TradingSystem.WebClient/src/components/AppBar.js, TradingSystem/TradingSystem.WebClient/src/components/EditProduct.js, TradingSystem/TradingSystem.WebClient/src/components/Navbar/Navbar.js, TradingSystem/TradingSystem.WebClient/src/components/Products.js, TradingSystem/TradingSystem.WebClient/src/components/SetPermission.js, TradingSystem/TradingSystem.WebClient/src/components/searchBar.js, TradingSystem/TradingSystem.WebClient/src/index.js, TradingSystem/TradingSystem.WebClient/src/pages/Login/Login.js, TradingSystem/TradingSystem.WebClient/src/pages/ShoppingCart/ShoppingCart.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/MyStores.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreHistory.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreList.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreProducts.js, TradingSystem/TradingSystem.WebClient/src/pages/mainPage/Home.css, TradingSystem/TradingSystem.WebClient/src/routes.js
* Adjusted the web API server to the changes in the service layer
* Done store products view
* Fixed navigation issues of store pages
* Fixed shopping cart page not accessible
* Fixed coding style issues and unused imports
#220 #221
=> Boaz client 

TradingSystem/TradingSystem.WebApi/Notifications/NotificationsMiddlewareExtensions.cs, TradingSystem/TradingSystem.WebApi/Notifications/Subscriber.cs, TradingSystem/TradingSystem.WebApi/Notifications/WebSocketHandler.cs, TradingSystem/TradingSystem.WebClient/src/App.js, TradingSystem/TradingSystem.WebClient/src/components/HomeProduct.js, TradingSystem/TradingSystem.WebClient/src/components/HomeProducts.js, TradingSystem/TradingSystem.WebClient/src/pages/ShoppingCart/ShoppingCart.js, TradingSystem/TradingSystem.WebClient/src/pages/mainPage/Home.js, TradingSystem/TradingSystem.WebClient/src/routes.js
* Fixed a bug in the home page related to the quantity input for each product
* Changed live notification content
* Open store notification is not sent by the web server
=> Boaz client fixes

TradingSystem/TradingSystem.WebApi/Controllers/HistoryController.cs, TradingSystem/TradingSystem.WebApi/Controllers/StoresController.cs, TradingSystem/TradingSystem.WebApi/DTO/History/ProductHistoryDTO.cs, TradingSystem/TradingSystem.WebApi/DTO/History/ShoppingBasketHistoryDTO.cs, TradingSystem/TradingSystem.WebApi/DTO/Store/StoreNameDTO.cs, TradingSystem/TradingSystem.WebClient/src/api.js, TradingSystem/TradingSystem.WebClient/src/components/HomeProducts.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Store.css, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Store.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreListUserView.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreProductsUserView.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/searchStore.js, TradingSystem/TradingSystem.WebClient/src/pages/mainPage/Home.js, TradingSystem/TradingSystem.WebClient/src/utils.js
* History web API
* Store products view
* Search store by name
=> Client logic continue

TradingSystem/TradingSystem.WebApi/Controllers/HistoryController.cs, TradingSystem/TradingSystem.WebApi/DTO/History/HistoryRecordDTO.cs, TradingSystem/TradingSystem.WebApi/DTO/History/StoreHistorySpecificDTO.cs, TradingSystem/TradingSystem.WebApi/DTO/InfoActionDTO.cs, TradingSystem/TradingSystem.WebClient/src/api.js, TradingSystem/TradingSystem.WebClient/src/components/History.js, TradingSystem/TradingSystem.WebClient/src/components/Navbar/Navbar.js, TradingSystem/TradingSystem.WebClient/src/components/Navbar/SidebarData.js, TradingSystem/TradingSystem.WebClient/src/components/searchBar.js, TradingSystem/TradingSystem.WebClient/src/data/historyData.json, TradingSystem/TradingSystem.WebClient/src/globalContext.js, TradingSystem/TradingSystem.WebClient/src/pages/Admin/AdminHistory.js, TradingSystem/TradingSystem.WebClient/src/pages/History/HistoryProduct.js, TradingSystem/TradingSystem.WebClient/src/pages/History/HistoryProductsList.js, TradingSystem/TradingSystem.WebClient/src/pages/History/UserHistory.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreHistory.js, TradingSystem/TradingSystem.WebClient/src/utils.js
* Imeplemented history logic in the clien
* Implemented admin specific actions (only view history right now)
=> Client - history logic

TradingSystem/TradingSystem.WebClient/src/header.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/AddCopmlexDiscount.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/Discounts.css, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/SimpleDiscount.js
=> minox fix in presentation discounts

TradingSystem/TradingSystem.WebClient/src/components/Navbar/SidebarData.js, TradingSystem/TradingSystem.WebClient/src/data/bidsData.json, TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreBids/AddBid.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreBids/storeBids.css, TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreBids/storeBids.js, TradingSystem/TradingSystem.WebClient/src/pages/UserBids/BidRecord.js, TradingSystem/TradingSystem.WebClient/src/pages/UserBids/userBids.css, TradingSystem/TradingSystem.WebClient/src/pages/UserBids/userBids.js, TradingSystem/TradingSystem.WebClient/src/routes.js
=> Bids Presentation

TradingSystem/TradingSystem.WebApi/Controllers/ShoppingCartController.cs, TradingSystem/TradingSystem.WebApi/DTO/ShoppingCart/ShoppingBasketDTO.cs, TradingSystem/TradingSystem.WebApi/DTO/ShoppingCart/ShoppingCartDTO.cs, TradingSystem/TradingSystem.WebClient/src/components/CartProduct.js, TradingSystem/TradingSystem.WebClient/src/components/CartProducts.js, TradingSystem/TradingSystem.WebClient/src/components/HomeProduct.js, TradingSystem/TradingSystem.WebClient/src/components/HomeProducts.js, TradingSystem/TradingSystem.WebClient/src/components/Navbar/SidebarData.js, TradingSystem/TradingSystem.WebClient/src/pages/History/HistoryProducts.js, TradingSystem/TradingSystem.WebClient/src/pages/ShoppingCart/ShoppingCart.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreCreateForm.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/StoreProductsUserView.js, TradingSystem/TradingSystem.WebClient/src/utils.js
Minor fixes in the client:
* Irrelevant sidebar buttons showing for guest users
* Total price for shopping cart is now fetched from the server
* Store products view - removed redundant label
* Fixed error message alert showing weird messages
=> Client minor fixes

TradingSystem/AcceptanceTests/Init_Test.cs, TradingSystem/TradingSystem/Service/SetupService.cs, TradingSystem/TradingSystem/init.txt
=> pretty toffee

TradingSystem/TradingSystem.WebApi/Controllers/StoreRulesController.cs, TradingSystem/TradingSystem.WebApi/DTO/Store/Discounts/DiscountDataDTO.cs, TradingSystem/TradingSystem.WebApi/DTO/Store/Policy/PolicyDataDTO.cs, TradingSystem/TradingSystem.WebApi/DTO/Store/Policy/PolicyParamsDTO.cs, TradingSystem/TradingSystem.WebClient/src/api.js, TradingSystem/TradingSystem.WebClient/src/components/HomeProduct.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Policy/AddPolicy.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Policy/Policy.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Policy/PolicyRecord.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Store.css, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Store.js, TradingSystem/TradingSystem.WebClient/src/routes.js, TradingSystem/TradingSystem.WebClient/src/utils.js
* Implemented policies in the client
=> Boaz client policies

TradingSystem/TradingSystem.WebApi/Controllers/StoreRulesController.cs, TradingSystem/TradingSystem.WebApi/DTO/Store/Discounts/DiscountDataCompundDTO.cs, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/AddCopmlexDiscount.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/ComplexDiscount.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/Discounts.js
* Complex discount decide field display fix
* Serial number on compound discounts
* Compound discount composed of other compound discounts
=> Boaz client discount fixes

TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/Discounts.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/SimpleDiscount.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Policy/Policy.js
* Fixed discount and policy pages may raise exceptions if the requests to the web API didn't complete in time
=> Client - exception fix (page not ready)

TradingSystem/TradingSystem.WebClient/src/pages/Stores/Discount/SimpleDiscount.js, TradingSystem/TradingSystem.WebClient/src/pages/Stores/Policy/PolicyRecord.js
* Fixed product and category can show even if rule type was not on 'Quantity'
=> Client - discount and policy displays
